#! /bin/sh

#declare functions
function usage ()
{
   cat << EOF
Usage: $0 [-s symbol] [-h] tbl-file term-file
Parameters:
  -s symbol    define startsymbol
  -h           display this message
EOF
exit 0
}

function error ()
{
  echo error: $1
  exit 1
}

#process options
while getopts ":hs:" opt; do
   case $opt in
   \? ) usage;;
   h )  usage;;
   s )  startsymbol=$OPTARG;;
   esac
done
shift $(($OPTIND - 1))

#check validity of file arguments
if [ $# -ne 2 ]; then usage; fi
if [ ! -e $1 ];  then error "file $1 does not exist"; fi  
if [ ! -e $2 ];  then error "file $2 does not exist"; fi

#parse term $2 using sdf parse table $1
term=$(sed -e 's/\(.*\)\.[a-z0-9]*$/\1/' <<< $2)
sglr -v -t ${startsymbol:+-s $startsymbol} -p $1 -i $2 -o ${term}.tree
if [ -e ${term}.tree ]; then
  ParseError=$(grep 'parse-error' ${term}.tree)
  if [ -z "$ParseError" ]; then
    echo "wrote parse tree to ${term}.tree"
    exit 0
  else
    cat <<< $ParseError
    exit 1
  fi
else 
  exit 1
fi
