// Author(s): Wieger Wesselink
// Copyright: see the accompanying file COPYING or copy at
// https://svn.win.tue.nl/trac/MCRL2/browser/trunk/COPYING
//
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)
//
/// \file mcrl2/atermpp/aterm_make_match.h
/// \brief Includes for make_term and match.

#ifndef MCRL2_ATERMPP_ATERM_MAKE_MATCH_H
#define MCRL2_ATERMPP_ATERM_MAKE_MATCH_H

#include "mcrl2/atermpp/aterm.h"

namespace atermpp
{
  /// \brief Make a term from a string pattern.
  /// \param pattern A string
  /// \return The term constructed from the pattern.
  inline
  aterm make_term(const std::string& pattern)
  {
    return aterm(ATreadFromString(const_cast<char*>(pattern.c_str())));
  }

#include "mcrl2/atermpp/aterm_make.h"    // generated by preprocessor
#include "mcrl2/atermpp/aterm_match.h"   // generated by preprocessor

} // namespace atermpp

#endif // MCRL2_ATERMPP_ATERM_MAKE_MATCH_H
