.. |bin_w64n| replace:: |download_nightly_pre|\ |version|\ |bin_w64n_post|

.. |bin_w64n_post| raw:: html

    _AMD64.exe">Windows Installer (64-bit)</a>


.. |zip_w64n| replace:: |download_nightly_pre|\ |version|\ |zip_w64n_post|

.. |zip_w64n_post| raw:: html

    _AMD64.zip">Windows ZIP (64-bit)</a>


.. |bin_deb32n| replace:: |download_nightly_pre|\ |version|\ |bin_deb32n_post|

.. |bin_deb32n_post| raw:: html

    _i686.deb">Ubuntu DEB (32-bit)</a>


.. |bin_deb64n| replace:: |download_nightly_pre|\ |version|\ |bin_deb64n_post|

.. |bin_deb64n_post| raw:: html

    _x86_64.deb">Ubuntu DEB (64-bit)</a>


.. |bin_fedora64n| replace:: |download_nightly_pre|\ |version|\ |bin_fedora64n_post|

.. |bin_fedora64n_post| raw:: html

    _x86_64.rpm">Fedora RPM (64-bit)</a>


.. |bin_osx64n| replace:: |download_nightly_pre|\ |version|\ |bin_osx64n_post|

.. |bin_osx64n_post| raw:: html

    _x86_64.dmg">macOS DMG (x86_64)</a>

.. |bin_osx_arm64n| replace:: |download_nightly_pre|\ |version|\ |bin_osx_arm64n_post|

.. |bin_osx_arm64n_post| raw:: html

    _arm64.dmg">macOS DMG (ARM64)</a>

.. |src_tgzn| replace:: |download_nightly_pre|\ |version|\ |src_tgzn_post|

.. |src_tgzn_post| raw:: html

    .tar.gz">GZipped Tarball</a>


.. |download_nightly_pre| raw:: html

    <a href="https://www.mcrl2.org/download/devel/mcrl2-
