.. |bin_w64| replace:: |download_release_pre|\ |release|\ |bin_w64_post|

.. |bin_w64_post| raw:: html

    _x86_64.exe">Windows Installer (64-bit)</a>


.. |zip_w64| replace:: |download_release_pre|\ |release|\ |zip_w64_post|

.. |zip_w64_post| raw:: html

    _x86_64.zip">Windows ZIP (64-bit)</a>


.. |bin_osx| replace:: |download_release_pre|\ |release|\ |bin_osx_post|

.. |bin_osx_post| raw:: html

    _x86_64.dmg">macOS DMG (x86_64)</a>


.. |bin_osx_arm| replace:: |download_release_pre|\ |release|\ |bin_osx_arm_post|

.. |bin_osx_arm_post| raw:: html

    _arm64.dmg">macOS DMG (ARM64)</a>
    


.. |bin_ppa| replace:: Ubuntu PPA release
.. _bin_ppa: https://launchpad.net/~mcrl2/+archive/release-ppa


.. |bin_fedora64| replace:: |download_release_pre|\ |release|\ |bin_fedora64_post|

.. |bin_fedora64_post| raw:: html

    _x86_64.rpm">Fedora RPM (64-bit)</a>


.. |src_tgz| replace:: |download_release_pre|\ |release|\ |src_tgz_post|

.. |src_tgz_post| raw:: html

    .tar.gz">GZipped Tarball</a>


.. |download_release_pre| raw:: html

    <a href="https://www.mcrl2.org/download/release/mcrl2-
