// ======================================================================
//
// Copyright (c) 2004, 2005, 2006 Wieger Wesselink
//
// ----------------------------------------------------------------------
//
// file          : atermpp/aterm_make_match.h
// date          : 28-11-2006
// version       : 1.0
//
// author(s)     : Wieger Wesselink  <J.W.Wesselink@tue.nl>
//
// ======================================================================

///////////////////////////////////////////////////////////////////////////////
/// \file atermpp/aterm_make_match.h
/// This file contains implementations for aterm_make and aterm_match.

#ifndef ATERM_MAKE_MATCH_H
#define ATERM_MAKE_MATCH_H

#include "atermpp/aterm.h"

namespace atermpp
{
  //---------------------------------------------------------//
  //             aterm_make / aterm_match
  //---------------------------------------------------------//
  
  inline
  aterm make_term(const std::string& pattern)
  {
    return aterm(ATreadFromString(const_cast<char*>(pattern.c_str())));
  }

#include "atermpp/aterm_make.h"    // generated by preprocessor
#include "atermpp/aterm_match.h"   // generated by preprocessor

} // namespace atermpp

#endif // ATERM_MAKE_MATCH_H
