.\" Manual page for mcrl2compilerewriter .\"
.TH MCRL2COMPILEREWRITER "1" "July 2011" "mcrl2compilerewriter mCRL2 toolset January 2012 (development)" "User Commands"
.SH NAME
mcrl2compilerewriter \- compile a rewriter for an mCRL2 tool
.SH SYNOPSIS
.B mcrl2compilerewriter
\fIINFILE\fR
.SH DESCRIPTION
This script is the default script to compile rewriter libraries for mCRL2.
It compiles the source file in INFILE. The output consists of a newline separated
list of files. The last file in the list is treated as the compiler library,
and must be a valid executable. All files listed in the output are deleted by
the mCRL2 tool that calls this script, once the library is no longer needed.

To change compiling behaviour, follow the following steps:
.br
- Create a new script (perhaps based on the original one)
.br
- Let the MCRL2_COMPILE_REWRITER environment variable point to the new script.

.SH AUTHOR
Written by Sjoerd Cranen.
.SH "REPORTING BUGS"
Report bugs at <http://www.mcrl2.org/issuetracker>.
.SH COPYRIGHT
Copyright \(co 2011 Technische Universiteit Eindhoven.
.br
This is free software.  You may redistribute copies of it under the
terms of the Boost Software License <http://www.boost.org/LICENSE_1_0.txt>.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
See also the manual at <http://www.mcrl2.org/mcrl2/wiki/index.php/User_manual>.
