XMLTO      = xmlto
OBJECTS    = libgsrewrite.7

all: $(OBJECTS)

%.1: %.xml
	xmlto man $<

%.2: %.xml
	xmlto man $<

%.3: %.xml
	xmlto man $<

%.4: %.xml
	xmlto man $<

%.5: %.xml
	xmlto man $<

%.6: %.xml
	xmlto man $<

%.7: %.xml
	xmlto man $<

%.8: %.xml
	xmlto man $<

%.9: %.xml
	xmlto man $<
