// Author(s): Wieger Wesselink
//
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)
//
/// \file atermpp/aterm_make_match.h
/// \brief Add your file description here.

#ifndef MCRL2_ATERMPP_ATERM_MAKE_MATCH_H
#define MCRL2_ATERMPP_ATERM_MAKE_MATCH_H

#include "atermpp/aterm.h"

namespace atermpp
{
  //---------------------------------------------------------//
  //             aterm_make / aterm_match
  //---------------------------------------------------------//
  
  inline
  aterm make_term(const std::string& pattern)
  {
    return aterm(ATreadFromString(const_cast<char*>(pattern.c_str())));
  }

#include "atermpp/aterm_make.h"    // generated by preprocessor
#include "atermpp/aterm_match.h"   // generated by preprocessor

} // namespace atermpp

#endif // MCRL2_ATERMPP_ATERM_MAKE_MATCH_H
