message(STATUS "CMAKE VERSION: ${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}.${CMAKE_PATCH_VERSION}")
message(STATUS "CMAKE_BUILD_TYPE: ${CMAKE_BUILD_TYPE} " )
message(STATUS "CMAKE_INSTALL_PREFIX: ${CMAKE_INSTALL_PREFIX}")
message(STATUS "BUILD_SHARED_LIBS: ${BUILD_SHARED_LIBS}")
message(STATUS "MCRL2_ENABLE_EXPERIMENTAL: ${MCRL2_ENABLE_EXPERIMENTAL}" )
message(STATUS "MCRL2_ENABLE_DEPRECATED: ${MCRL2_ENABLE_DEPRECATED}" )
message(STATUS "MCRL2_INSTALL_HEADERS: ${MCRL2_INSTALL_HEADERS}" )
message(STATUS "** Compiler version: CXX: ${CXX_COMPILER_VERSION} ${CXX_COMPILER_ARCHITECTURE}")
message(STATUS "**                   C:   ${C_COMPILER_VERSION}")
if(MCRL2_GNU)
  message(STATUS "** Using GNU compiler configuration")
  if(MCRL2_CLANG)
    message(STATUS "** Using Clang compiler configuration")
  endif()
endif()
if(MCRL2_MSVC)
  message(STATUS "** Using MSVC compiler configuration")
endif()
message(STATUS "** mCRL2 version: ${MCRL2_VERSION}")
message(STATUS "** Last SVN change: ${Project_WC_LAST_CHANGED_DATE}")
message(STATUS "** CVC3 version: ${cvc3_VERSION}")

