import os

os.system('mcrl22lps -vo othello.mcrl2 othello.lps')
os.system('lpssuminst -v -rjitty othello.lps temp0.lps')
os.system('lpsparunfold -n6 -lv -sBoard temp0.lps > temp1.lps')
os.system('lpsrewr -v -rjitty temp1.lps | lpsconstelm -c -v | lpsrewr -v > temp2.lps')
os.system('lpsparunfold -n6 -lv -sRow temp2.lps > temp3.lps')
os.system('lpsrewr -v -rjitty temp3.lps temp4.lps')
os.system('lpsconstelm -c -v -rjitty temp4.lps temp4a.lps')
os.system('lpsrewr -v -rjitty temp4a.lps temp5.lps')
os.system('lps2lts -v -rjitty temp5.lps')
os.system('echo ----------------------------------------------')
os.system('echo Red can always win, i.e. red has a winning strategy.')
os.system('echo ---------------------------------------------- ')
os.system('lps2pbes -v -fred_wins_always.mcf temp5.lps othello.pbes')
os.system('pbes2bool -v -rjitty othello.pbes')
os.system('echo ----------------------------------------------')
os.system('echo White can always win, i.e. white has a winning strategy.')
os.system('echo ----------------------------------------------')
os.system('lps2pbes -v -fwhite_wins_always.mcf temp5.lps othello.pbes')
os.system('pbes2bool -v -rjitty othello.pbes')
os.system('echo ----------------------------------------------')
os.system('echo Nodeadlock.')
os.system('echo ----------------------------------------------')
os.system('lps2pbes -v -fnodeadlock.mcf temp5.lps othello.pbes')
os.system('pbes2bool -v -rjitty othello.pbes')
os.system('echo ----------------------------------------------')
os.system('echo There exists a draw.')
os.system('echo ----------------------------------------------')
os.system('lps2pbes -v -fexists_draw.mcf temp5.lps othello.pbes')
os.system('pbes2bool -v -rjitty othello.pbes')
os.system('echo ----------------------------------------------')
os.system('echo White can win.')
os.system('echo ----------------------------------------------')
os.system('lps2pbes -v -fwhite_can_win.mcf temp5.lps othello.pbes')
os.system('pbes2bool -v -rjitty othello.pbes')
os.system('echo ----------------------------------------------')
os.system('echo Red can win.')
os.system('echo ----------------------------------------------')
os.system('lps2pbes -v -fred_can_win.mcf temp5.lps othello.pbes')
os.system('pbes2bool -v -rjitty othello.pbes')
os.system('echo ----------------------------------------------')
os.system('echo ----------------------------------------------')

