#ifndef MCRL2_HEADERTEST_HEADER_NAME
#error "MCRL2_HEADERTEST_HEADER_NAME must be defined via -DMCRL2_HEADERTEST_HEADER_NAME=<header path>"
#endif

#define MCRL2_HEADERTEST_STRINGIZE_IMPL(x) #x
#define MCRL2_HEADERTEST_STRINGIZE(x) MCRL2_HEADERTEST_STRINGIZE_IMPL(x)

#define MCRL2_HEADERTEST_HEADER MCRL2_HEADERTEST_STRINGIZE(MCRL2_HEADERTEST_HEADER_NAME)

#include MCRL2_HEADERTEST_HEADER

int main()
{}
