.. |bin_w32| replace:: Windows Installer (32-bit)
.. _bin_w32: http://www.mcrl2.org/download/release/mcrl2-201210.1_x86.exe

.. |bin_w64| replace:: Windows Installer (64-bit)
.. _bin_w64: http://www.mcrl2.org/download/release/mcrl2-201210.1_x86_64.exe

.. |bin_osx| replace:: Darwin package
.. _bin_osx: http://www.mcrl2.org/download/release/mcrl2-201210.1-Darwin.dmg

.. |bin_ppa| replace:: PPA release
.. _bin_ppa: https://launchpad.net/~mcrl2/+archive/release-ppa

.. |src_tgz| replace:: GZipped Tarball
.. _src_tgz: http://www.mcrl2.org/download/release/mcrl2-201210.1.tar.gz
